### PR TITLE
e2e: fix disable and undeploy actions if resources not found

### LINKED ISSUE #1878: e2e: Undeploy fail is resources is not found
To clean up clusters after failed tests, we can use:

```console
% ./run.sh -test.run ///Undeploy
```

However it fails when some resource is not found:

```
2025-03-03T12:50:59.161+0200	ERROR	subscr-deploy-rbd-busybox	Failed to undeploy workload: placements.cluster.open-cluster-management.io "subscr-deploy-rbd-busybox" not found
2025-03-03T12:50:59.161+0200	ERROR	appset-deploy-rbd-busybox	Failed to undeploy workload: placements.cluster.open-cluster-management.io "appset-deploy-rbd-busybox" not found
2025-03-03T12:50:59.162+0200	ERROR	appset-deploy-cephfs-busybox	Failed to undeploy workload: placements.cluster.open-cluster-management.io "appset-deploy-cephfs-busybox" not found
2025-03-03T12:50:59.163+0200	ERROR	subscr-deploy-cephfs-busybox	Failed to undeploy workload: placements.cluster.open-cluster-management.io "subscr-deploy-cephfs-busybox" not found
...
--- FAIL: TestSuites (0.03s)
    --- PASS: TestSuites/Validate (0.03s)
        --- PASS: TestSuites/Validate/hub (0.01s)
        --- PASS: TestSuites/Validate/c1 (0.01s)
        --- PASS: TestSuites/Validate/c2 (0.01s)
    --- FAIL: TestSuites/Exhaustive (6.04s)
        --- FAIL: TestSuites/Exhaustive/subscr-deploy-rbd-busybox (0.01s)
            --- FAIL: TestSuites/Exhaustive/subscr-deploy-rbd-busybox/Undeploy (0.01s)
        --- FAIL: TestSuites/Exhaustive/appset-deploy-rbd-busybox (0.01s)
            --- FAIL: TestSuites/Exhaustive/appset-deploy-rbd-busybox/Undeploy (0.01s)
        --- FAIL: TestSuites/Exhaustive/appset-deploy-cephfs-busybox (0.01s)
            --- FAIL: TestSuites/Exhaustive/appset-deploy-cephfs-busybox/Undeploy (0.01s)
        --- FAIL: TestSuites/Exhaustive/subscr-deploy-cephfs-busybox (0.01s)
            --- FAIL: TestSuites/Exhaustive/subscr-deploy-cephfs-busybox/Undeploy (0.01s)
        --- PASS: TestSuites/Exhaustive/disapp-deploy-cephfs-busybox (2.52s)
            --- PASS: TestSuites/Exhaustive/disapp-deploy-cephfs-busybox/Undeploy (2.52s)
        --- PASS: TestSuites/Exhaustive/disapp-deploy-rbd-busybox (8.53s)
            --- PASS: TestSuites/Exhaustive/disapp-deploy-rbd-busybox/Undeploy (8.53s)
FAIL
```

Undeploy must be idempotent, if resources is not found we should log a debug message and continue.

Required for ramenctl.

### LINKED ISSUE #1879: e2e: Disable fail if resources is not found
To clean up cluster after failed tests we can use:

```console
./run.sh -test.run ///Disable
```

But like #1878 Disable fail if resource is not fund:

```console
2025-03-03T12:56:47.485+0200	ERROR	disapp-deploy-cephfs-busybox	Failed to disable protection for workload: placements.cluster.open-cluster-management.io "disapp-deploy-cephfs-busybox" not found
2025-03-03T12:56:47.487+0200	ERROR	appset-deploy-cephfs-busybox	Failed to disable protection for workload: placements.cluster.open-cluster-management.io "appset-deploy-cephfs-busybox" not found
2025-03-03T12:56:47.487+0200	ERROR	subscr-deploy-cephfs-busybox	Failed to disable protection for workload: placements.cluster.open-cluster-management.io "subscr-deploy-cephfs-busybox" not found
2025-03-03T12:56:47.487+0200	ERROR	appset-deploy-rbd-busybox	Failed to disable protection for workload: placements.cluster.open-cluster-management.io "appset-deploy-rbd-busybox" not found
2025-03-03T12:56:47.487+0200	ERROR	subscr-deploy-rbd-busybox	Failed to disable protection for workload: placements.cluster.open-cluster-management.io "subscr-deploy-rbd-busybox" not found
2025-03-03T12:56:47.489+0200	INFO	disapp-deploy-rbd-busybox	Unprotecting workload running in cluster "dr
...
--- FAIL: TestSuites (0.02s)
    --- PASS: TestSuites/Validate (0.02s)
        --- PASS: TestSuites/Validate/hub (0.01s)
        --- PASS: TestSuites/Validate/c1 (0.01s)
        --- PASS: TestSuites/Validate/c2 (0.01s)
    --- FAIL: TestSuites/Exhaustive (6.03s)
        --- FAIL: TestSuites/Exhaustive/disapp-deploy-cephfs-busybox (0.00s)
            --- FAIL: TestSuites/Exhaustive/disapp-deploy-cephfs-busybox/Disable (0.00s)
        --- FAIL: TestSuites/Exhaustive/appset-deploy-cephfs-busybox (0.01s)
            --- FAIL: TestSuites/Exhaustive/appset-deploy-cephfs-busybox/Disable (0.01s)
        --- FAIL: TestSuites/Exhaustive/subscr-deploy-cephfs-busybox (0.01s)
            --- FAIL: TestSuites/Exhaustive/subscr-deploy-cephfs-busybox/Disable (0.01s)
        --- FAIL: TestSuites/Exhaustive/appset-deploy-rbd-busybox (0.01s)
            --- FAIL: TestSuites/Exhaustive/appset-deploy-rbd-busybox/Disable (0.01s)
        --- FAIL: TestSuites/Exhaustive/subscr-deploy-rbd-busybox (0.01s)
            --- FAIL: TestSuites/Exhaustive/subscr-deploy-rbd-busybox/Disable (0.01s)
        --- PASS: TestSuites/Exhaustive/disapp-deploy-rbd-busybox (55.07s)
            --- PASS: TestSuites/Exhaustive/disapp-deploy-rbd-busybox/Disable (55.07s)
```

Disable must be idempotent and succeeds after successful completion.

### PR DESCRIPTION
**Pull request by parikshithb**
This change ensures that undeploy and disable actions handle missing placement resources gracefully when calling GetCurrentCluster, making them idempotent. This is required for ramenctl aswell.

Tests done without existing resources(rebased and updated):
1. `./run.sh -test.run TestDR//Undeploy`
```
2025-03-10T20:02:13.148+0530	INFO	subscr-deploy-cephfs-busybox	Undeploying subscription app "e2e-subscr-deploy-cephfs-busybox/busybox"
2025-03-10T20:02:13.148+0530	INFO	appset-deploy-rbd-busybox	Undeploying applicationset app "e2e-appset-deploy-rbd-busybox/busybox"
2025-03-10T20:02:13.148+0530	INFO	subscr-deploy-rbd-busybox	Undeploying subscription app "e2e-subscr-deploy-rbd-busybox/busybox"
2025-03-10T20:02:13.148+0530	INFO	appset-deploy-cephfs-busybox	Undeploying applicationset app "e2e-appset-deploy-cephfs-busybox/busybox"
2025-03-10T20:02:13.150+0530	INFO	disapp-deploy-rbd-busybox	Undeploying discovered app "e2e-disapp-deploy-rbd-busybox/busybox" in clusters "dr1" and "dr2"
2025-03-10T20:02:13.150+0530	INFO	disapp-deploy-cephfs-busybox	Undeploying discovered app "e2e-disapp-deploy-cephfs-busybox/busybox" in clusters "dr1" and "dr2"
2025-03-10T20:02:13.160+0530	INFO	appset-deploy-cephfs-busybox	Workload undeployed
2025-03-10T20:02:13.161+0530	INFO	subscr-deploy-rbd-busybox	Workload undeployed
2025-03-10T20:02:13.161+0530	INFO	appset-deploy-rbd-busybox	Workload undeployed
2025-03-10T20:02:13.162+0530	INFO	subscr-deploy-cephfs-busybox	Workload undeployed
2025-03-10T20:02:18.524+0530	INFO	disapp-deploy-cephfs-busybox	Workload undeployed
2025-03-10T20:02:18.647+0530	INFO	disapp-deploy-rbd-busybox	Workload undeployed
2025-03-10T20:02:18.649+0530	INFO	Deleted channel "e2e-gitops/https-github-com-ramendr-ocm-ramen-samples-git" in cluster "hub"
--- PASS: TestDR (6.03s)
    --- PASS: TestDR/appset-deploy-cephfs-busybox (0.02s)
        --- PASS: TestDR/appset-deploy-cephfs-busybox/Undeploy (0.02s)
    --- PASS: TestDR/subscr-deploy-rbd-busybox (0.02s)
        --- PASS: TestDR/subscr-deploy-rbd-busybox/Undeploy (0.02s)
    --- PASS: TestDR/appset-deploy-rbd-busybox (0.02s)
        --- PASS: TestDR/appset-deploy-rbd-busybox/Undeploy (0.02s)
    --- PASS: TestDR/subscr-deploy-cephfs-busybox (0.02s)
        --- PASS: TestDR/subscr-deploy-cephfs-busybox/Undeploy (0.02s)
    --- PASS: TestDR/disapp-deploy-cephfs-busybox (5.38s)
        --- PASS: TestDR/disapp-deploy-cephfs-busybox/Undeploy (5.38s)
    --- PASS: TestDR/disapp-deploy-rbd-busybox (5.50s)
        --- PASS: TestDR/disapp-deploy-rbd-busybox/Undeploy (5.50s)
```
2. `./run.sh -test.run TestDR//Disable`
```
2025-03-10T20:02:30.463+0530	INFO	appset-deploy-rbd-busybox	Unprotecting workload "e2e-appset-deploy-rbd-busybox/busybox"
2025-03-10T20:02:30.463+0530	INFO	appset-deploy-cephfs-busybox	Unprotecting workload "e2e-appset-deploy-cephfs-busybox/busybox"
2025-03-10T20:02:30.464+0530	INFO	disapp-deploy-rbd-busybox	Unprotecting workload "e2e-disapp-deploy-rbd-busybox/busybox"
2025-03-10T20:02:30.464+0530	INFO	disapp-deploy-cephfs-busybox	Unprotecting workload "e2e-disapp-deploy-cephfs-busybox/busybox"
2025-03-10T20:02:30.464+0530	INFO	subscr-deploy-cephfs-busybox	Unprotecting workload "e2e-subscr-deploy-cephfs-busybox/busybox"
2025-03-10T20:02:30.464+0530	INFO	subscr-deploy-rbd-busybox	Unprotecting workload "e2e-subscr-deploy-rbd-busybox/busybox"
2025-03-10T20:02:30.467+0530	INFO	subscr-deploy-cephfs-busybox	Workload unprotected
2025-03-10T20:02:30.467+0530	INFO	subscr-deploy-rbd-busybox	Workload unprotected
2025-03-10T20:02:30.471+0530	INFO	disapp-deploy-cephfs-busybox	Workload unprotected
2025-03-10T20:02:30.471+0530	INFO	disapp-deploy-rbd-busybox	Workload unprotected
2025-03-10T20:02:30.667+0530	INFO	appset-deploy-rbd-busybox	Workload unprotected
2025-03-10T20:02:30.867+0530	INFO	appset-deploy-cephfs-busybox	Workload unprotected
2025-03-10T20:02:30.869+0530	INFO	Deleted channel "e2e-gitops/https-github-com-ramendr-ocm-ramen-samples-git" in cluster "hub"
--- PASS: TestDR (6.03s)
    --- PASS: TestDR/subscr-deploy-cephfs-busybox (0.01s)
        --- PASS: TestDR/subscr-deploy-cephfs-busybox/Disable (0.01s)
    --- PASS: TestDR/subscr-deploy-rbd-busybox (0.01s)
        --- PASS: TestDR/subscr-deploy-rbd-busybox/Disable (0.01s)
    --- PASS: TestDR/disapp-deploy-cephfs-busybox (0.01s)
        --- PASS: TestDR/disapp-deploy-cephfs-busybox/Disable (0.01s)
    --- PASS: TestDR/disapp-deploy-rbd-busybox (0.01s)
        --- PASS: TestDR/disapp-deploy-rbd-busybox/Disable (0.01s)
    --- PASS: TestDR/appset-deploy-rbd-busybox (0.21s)
        --- PASS: TestDR/appset-deploy-rbd-busybox/Disable (0.21s)
    --- PASS: TestDR/appset-deploy-cephfs-busybox (0.41s)
        --- PASS: TestDR/appset-deploy-cephfs-busybox/Disable (0.41s)
```
3. Added debug log example:
```
DEBUG   appset-deploy-rbd-busybox       deployers/appset.go:66  Could not retrieve the cluster name: placements.cluster.open-cluster-management.io "appset-deploy-rbd-busybox" not found
```

Fixes #1878
Fixes #1879

### CODE REVIEW

**Review by nirs — COMMENTED** [review]
This is missleasding:

> This commit ensures GetCurrentCluster does not fail when the
placement resources are not found in disable and undeploy actions.

GetCurrentCluster still fails, the change is to handle the case when the policy does not exist and handle it gracefully.

File: e2e/deployers/appset.go [hunk 1]
```diff
@@ -7,6 +7,7 @@ import (
 	"github.com/ramendr/ramen/e2e/config"
 	"github.com/ramendr/ramen/e2e/types"
 	"github.com/ramendr/ramen/e2e/util"
+	"k8s.io/apimachinery/pkg/api/errors"
```
Comment (nirs) [inline e2e/deployers/appset.go:10]: We use also the standard errors package. Please use k8serrors when importing this package even if we don't use the stdlib errors package in a file. We want to use the same name for the same library in the entire project. This should be correct now in ramen code itself.

File: e2e/deployers/appset.go [hunk 2]
```diff
@@ -65,7 +66,11 @@ func (a ApplicationSet) Undeploy(ctx types.Context) error {
 
 	clusterName, err := util.GetCurrentCluster(util.Ctx.Hub, managementNamespace, name)
 	if err != nil {
-		return err
+		if !errors.IsNotFound(err) {
+			return err
+		}
```
Comment (nirs) [inline e2e/deployers/appset.go:71]: I think this call was removed in main, so this change is not needed.

But we may need the same change when calling GetCurrentCluster before DeleteApplicationSet(), since the application may already be deleted.

Lets start by rebasing on main.

**Review by nirs — COMMENTED** [review]
Need to rebase on main, test and review again.

File: e2e/deployers/appset.go (hunk 2 above)
Comment (parikshithb) [reply e2e/deployers/appset.go:64]: rebased, made changes and tested. Updated in description.

File: e2e/deployers/appset.go [hunk 3]
```diff
@@ -58,11 +59,16 @@ func (a ApplicationSet) Undeploy(ctx types.Context) error {
...
 	if err != nil {
-		return err
-	}
+		if !k8serrors.IsNotFound(err) {
+			return err
+		}
 
-	log.Infof("Undeploying applicationset app \"%s/%s\" in cluster %q",
-		ctx.AppNamespace(), ctx.Workload().GetAppName(), clusterName)
+		log.Debugf("Could not retrieve the cluster name, required resource not found: %s", err)
```
Comment (nirs) [inline e2e/deployers/appset.go:66]: Thanks for sharing the log:

> DEBUG   subscr-deploy-rbd-busybox       dractions/actions.go:110        Could not retrieve the cluster name, required resource not found: placements.cluster.open-cluster-management.io "subscr-deploy-rbd-busybox" not found

We can remove the ", required resource not found", because the error explains itself. We will have:

```console
DEBUG   subscr-deploy-rbd-busybox       dractions/actions.go:110        Could not retrieve the cluster name: placements.cluster.open-cluster-management.io "subscr-deploy-rbd-busybox" not found
```

**Review by nirs — COMMENTED** [review]
Looks good, but the log can be improved.

File: e2e/dractions/actions.go [hunk 4]
```diff
@@ -145,8 +151,7 @@ func Failover(ctx types.Context) error {
 		return err
 	}
 
-	log.Infof("Failing over workload \"%s/%s\" from cluster %q to cluster %q",
-		ctx.AppNamespace(), ctx.Workload().GetAppName(), currentCluster, targetCluster)
+	log.Infof("Failing over workload from cluster %q to cluster %q", currentCluster, targetCluster)
```
[the remark this answers is not in the document]
Comment (parikshithb) [reply e2e/dractions/actions.go]: Ack, will make changes in separate pr for all 'namespace/name' changes in info logs.

**Review by nirs — APPROVED** [review]
Thanks!

**Comment by nirs** [comment]
e2e failure is known issue, not related to this change.
