### PR TITLE
Change the hardcoded KUBEBUILDER_ASSETS to use dynamically detected os/arch

### LINKED ISSUE #765: Running unit tests fails on macos
The os architecture is hard-coded [here](https://github.com/RamenDR/ramen/blob/74c598bbc84d39dc8636340e20a6ce6c1680af25/controllers/suite_test.go#L117), [here](https://github.com/RamenDR/ramen/blob/74c598bbc84d39dc8636340e20a6ce6c1680af25/controllers/volsync/volsync_suite_test.go#L77), and [here](https://github.com/RamenDR/ramen/blob/74c598bbc84d39dc8636340e20a6ce6c1680af25/controllers/util/util_suite_test.go#L60).

A potential fix is:
```
Expect(os.Setenv("KUBEBUILDER_ASSETS",
	fmt.Sprintf("../../testbin/k8s/1.25.0-%s-%s", runtime.GOOS, runtime.GOARCH))).To(Succeed())
```

### PR DESCRIPTION
**Pull request by BenamarMk**
Fixes #765

### CODE REVIEW

File: controllers/volsync/volsync_suite_test.go [hunk 1]
```diff
@@ -74,7 +76,8 @@ var _ = BeforeSuite(func() {
 
 	By("Setting up KUBEBUILDER_ASSETS for envtest")
 	if _, set := os.LookupEnv("KUBEBUILDER_ASSETS"); !set {
-		Expect(os.Setenv("KUBEBUILDER_ASSETS", "../../testbin/k8s/1.25.0-linux-amd64")).To(Succeed())
+		Expect(os.Setenv("KUBEBUILDER_ASSETS",
+			fmt.Sprintf("../../testbin/k8s/1.25.0-%s-%s", runtime.GOOS, runtime.GOARCH))).To(Succeed())
```
Comment (nirs) [inline controllers/volsync/volsync_suite_test.go:80]: Which code is responsible for downloading `../../testbin/k8s/1.25.0-linux-amd64`?

Can we get the name of the file from that code?

Comment (BenamarMk) [reply controllers/volsync/volsync_suite_test.go:80]: Probably we can. I didn't want to bother with it. If you found out how to let me know.

Comment (BenamarMk) [reply controllers/volsync/volsync_suite_test.go:80]: For the code that downloads the file is "make envtest"
```
KUBEBUILDER_ASSETS="$(shell $(ENVTEST_ASSETS_DIR)/setup-envtest use $(ENVTEST_K8S_VERSION) --bin-dir $(ENVTEST_ASSETS_DIR) -p path)"
```

Comment (nirs) [reply controllers/volsync/volsync_suite_test.go:80]:
```
$ testbin/setup-envtest use --print path
/home/nsoffer/.local/share/kubebuilder-envtest/k8s/1.26.1-linux-amd64
```

Comment (BenamarMk) [reply controllers/volsync/volsync_suite_test.go:80]: Right, but what are you trying to get to in order to help this hapless PR?

Comment (BenamarMk) [reply controllers/volsync/volsync_suite_test.go:80]: Yeah, didn't want to spend too much time on this. Right now, I want my machine to be able to run unit tests.
Thanks for reviewing @nirs

Comment (ShyamsundarR) [reply controllers/volsync/volsync_suite_test.go:80]: @nirs (just adding some context) The `make test` is always run by setting the KUBEBUILDER_ASSETS from the Makefile, the change to add this directly within the code was to reuse environments where we wanted to run test outside the make commands. This combined with the makefile based tests defaulting to verbose logging, even I end up running `go test ...` rather than use the `make test` directive most often. At which point the current change is required for non-linux setups.
