### PR TITLE
Check specific conditions for MW and MCV

### LINKED ISSUE #173: ManifestWork status condition should check against "Applied" rather than "Available"
In a case where the resources in MW exist on the target cluster, the status of MW reads as `"Available" : true` but `"Applied"` is false, with errors on why the new resource was not applied.

We need to change how we process and assume a resource is applied to a cluster, as we check either condition as `true` and proceed.

This happened because of a stale PV left behind on one of the clusters, that caused a subsequent `relocate` to apply the PVs again, but the MW actually never was "applied" and hence the test failed (as the PVC got a new PV instead of binding to the existing PV).

### PR DESCRIPTION
**Pull request by ShyamsundarR**
Current code looks for duplicate conditions in MW and
MCV status and filters the most current ones.

Conditions typically do not have duplicate entries and
are maintained one per condition type. Also, looking at
MW and MCV reconcilers they do not seem to add muntiple
conditions.

Hence simplyfying the code to address only conditions by
type and not time stamps.

Further addressed checking for both 'applied' and 'available'
condition for MW to be deemed succesfully available on a
managed cluster.

Fixes #173

Signed-off-by: Shyamsundar Ranganathan <srangana@redhat.com>

### CODE REVIEW

File: controllers/drplacementcontrol_controller.go [hunk 1]
```diff
@@ -1502,22 +1502,20 @@ func (r *DRPlacementControlReconciler) getManagedClusterResource(
...
 	}
 
-	// get query results
-	recentConditions := rmnutil.GetMostRecentConditions(mcv.Status.Conditions)
+	r.Log.Info(fmt.Sprintf("MCV condtions: %v", mcv.Status.Conditions))
 
-	r.Log.Info(fmt.Sprintf("MCV recent condtions: %v", recentConditions))
 	// want single recent Condition with correct Type; otherwise: bad path
-	switch len(recentConditions) {
+	switch len(mcv.Status.Conditions) {
```
Comment (BenamarMk) [inline controllers/drplacementcontrol_controller.go:1508]: Doesn't this statement rarely produces the expected results.  IOW, doesn't this input take you to the default case even though it is a good input?
```
status:
  conditions:
  - lastTransitionTime: "2021-08-03T22:03:55Z"
    message: Apply manifest work complete
    reason: AppliedManifestWorkComplete
    status: "True"
    type: Applied
  - lastTransitionTime: "2021-08-03T22:03:56Z"
    message: All resources are available
    reason: ResourcesAvailable
    status: "True"
    type: Available
```

Comment (ShyamsundarR) [reply controllers/drplacementcontrol_controller.go:1508]: I checked the following sources to confirm the number of conditions:
1) view [doc](https://github.com/open-cluster-management/multicloud-operators-foundation/blob/main/docs/view/managedClusterView.md)
2) Code:
- [api](https://github.com/open-cluster-management/multicloud-operators-foundation/blob/dda6b80090951ca7abcc9bc8aca86d13c9202b26/pkg/apis/view/v1beta1/view_types.go#L92-L104)
- [reconcile code](https://github.com/open-cluster-management/multicloud-operators-foundation/blob/dda6b80090951ca7abcc9bc8aca86d13c9202b26/pkg/klusterlet/view/view_controller.go#L80-L156)

The above suggests that MCV will only have at most 1 condition, and hence the code above.

Am I looking at the wrong place? I checked my test cluster as well and did not see "ResourceAvailable" condition.

Checked the forked [repo](https://github.com/tjanssen3/multicloud-operators-foundation/tree/main/v2) as well for completeness and it remains as above.

Comment (BenamarMk) [reply controllers/drplacementcontrol_controller.go:1508]: You are right, only one condition.

**Review by BenamarMk — APPROVED** [review]
