### PR TITLE
Fix kubeobj protection ut

### LINKED ISSUE #1289: Fake s3 store in tests doesn't use locks to store data in a map
Recently, we have seen "concurrent map writes detected" error in our ginkgo tests. This is happening because the fake s3 store we have in the tests uses a simple map to store the data and doesn't use any lock to prevent concurrent writes.

We need to enhance the store to make it concurrency proof.

Line https://github.com/RamenDR/ramen/blob/main/controllers/s3utils_test.go#L93

### PR DESCRIPTION
**Pull request by pruthvitd**
Fixes #1289

### CODE REVIEW

File: internal/controller/s3utils_test.go [hunk 1]
```diff
@@ -90,8 +93,9 @@ func (f fakeObjectStorer) UploadObject(key string, object interface{}) error {
 		return awserr.New(s3.ErrCodeInvalidObjectState, "fake error uploading object", fmt.Errorf("fake error"))
 	}
 
+	mu.Lock()
 	f.objects[key] = object
-
+	mu.Unlock()
```
Comment (nirs) [inline internal/controller/s3utils_test.go:98]: We need to protect all accesses:
- set
- get
- delete
- iteration

Inserting or deleting items may trigger allocation or rebuilding of the map, and accessing it while it is being modified may return wrong results or panic.

File: internal/controller/s3utils_test.go [hunk 2]
```diff
@@ -35,6 +37,7 @@ const (
 )
 
 var fakeObjectStorers = make(map[string]fakeObjectStorer)
+var mu sync.Mutex
```
Comment (nirs) [inline internal/controller/s3utils_test.go:40]: The lock should part of fakeObjectStorer, not a global lock.

File: internal/controller/s3utils_test.go [hunk 3]
```diff
@@ -83,9 +85,13 @@ type fakeObjectStorer struct {
 	name       string
 	bucketName string
 	objects    map[string]interface{}
+	mu         sync.Mutex
```
Comment (nirs) [inline internal/controller/s3utils_test.go]: While this name is common, it is not a good name so we should not adapt it. `mutex` will make the code nicer without any bad effects.

File: internal/controller/s3utils_test.go [hunk 4]
```diff
@@ -68,10 +69,11 @@ func (fakeObjectStoreGetter) ObjectStore(
 
 	objectStorer, ok := fakeObjectStorers[s3ProfileName]
 	if !ok {
-		objectStorer = fakeObjectStorer{
+		objectStorer = &fakeObjectStorer{
 			name:       s3ProfileName,
 			bucketName: s3StoreProfile.S3Bucket,
 			objects:    make(map[string]interface{}),
+			mu:         sync.Mutex{},
```
Comment (nirs) [inline internal/controller/s3utils_test.go]: We don't need to initialize the mutex, the zero value of a mutex is good, basically what you added here.

File: internal/controller/s3utils_test.go [hunk 5]
```diff
@@ -128,21 +139,29 @@ func (f fakeObjectStorer) ListKeys(keyPrefix string) ([]string, error) {
 	return keys, nil
 }
 
-func (f fakeObjectStorer) DeleteObject(key string) error {
+func (f *fakeObjectStorer) DeleteObject(key string) error {
+	f.mu.Lock()
+	defer f.mu.Unlock()
```
Comment (nirs) [inline internal/controller/s3utils_test.go]: for consistency I would add blank line after the defer.

File: internal/controller/volumereplicationgroup_controller.go [hunk 6]
```diff
@@ -125,6 +125,8 @@ func (r *VolumeReplicationGroupReconciler) SetupWithManager(
 		r.Log.Info("Kube object protection disabled; don't watch kube objects requests")
 	}
 
+	r.recipeStatus = make(map[string]*util.RecipeStatus)
```
Comment (nirs) [inline internal/controller/volumereplicationgroup_controller.go]: Is this related?

**Review by nirs — COMMENTED** [review]
The looking changes looks right.

File: internal/controller/volumereplicationgroup_controller.go (hunk 6 above)
Comment (pruthvitd) [reply internal/controller/volumereplicationgroup_controller.go]: The current required rebase to sync with master. Its updated now.

File: internal/controller/s3utils_test.go [hunk 7]
```diff
@@ -68,10 +69,11 @@ func (fakeObjectStoreGetter) ObjectStore(
 
 	objectStorer, ok := fakeObjectStorers[s3ProfileName]
 	if !ok {
-		objectStorer = fakeObjectStorer{
+		objectStorer = &fakeObjectStorer{
 			name:       s3ProfileName,
 			bucketName: s3StoreProfile.S3Bucket,
 			objects:    make(map[string]interface{}),
+			mutex:         sync.Mutex{},
```
Comment (nirs) [inline internal/controller/s3utils_test.go]: Not needed, see comment in previous version.

File: internal/controller/s3utils_test.go [hunk 8]
```diff
@@ -83,9 +85,13 @@ type fakeObjectStorer struct {
 	name       string
 	bucketName string
 	objects    map[string]interface{}
+	mutex         sync.Mutex
```
Comment (nirs) [inline internal/controller/s3utils_test.go]: Formatting is off, looks like your editor is not configured properly. It format the file with `gofmt` or `golangci-lint fmt` when saving.

**Review by nirs — COMMENTED** [review]
The locking changes looks good, see comments.

File: internal/controller/s3utils_test.go (hunk 4 above)
Comment (nirs) [reply internal/controller/s3utils_test.go]: @pruthvitd you marked this as resolved, but it was not resolved.

File: internal/controller/s3utils_test.go (hunk 3 above)
Comment (pruthvitd) [reply internal/controller/s3utils_test.go]: Renamed to 'mutex'

File: internal/controller/s3utils_test.go (hunk 1 above)
Comment (pruthvitd) [reply internal/controller/s3utils_test.go]: Done.

File: internal/controller/s3utils_test.go (hunk 2 above)
Comment (pruthvitd) [reply internal/controller/s3utils_test.go]: Agreed. Made the suggested changes.

File: internal/controller/s3utils_test.go (hunk 8 above)
Comment (pruthvitd) [reply internal/controller/s3utils_test.go]: Formatting is fixed. Thanks for the comment.

File: internal/controller/s3utils_test.go (hunk 4 above)
Comment (pruthvitd) [reply internal/controller/s3utils_test.go]: I thought this initialization does the same, hence no changes were made. Anyways all the review comments are addressed now.
