### PR TITLE
UT fix for vshandler-test

### LINKED ISSUE #1812: volsync unit test VolSync_Handler Reconcile ReplicationSource intermittent failure
```
• [FAILED] [0.010 seconds]
VolSync_Handler Reconcile ReplicationSource When reconciling RSSpec When the psk secret for volsync exists (will be pushed down by drpc from hub When no running pod is mounting the PVC to be protected [It] Should return a replication source and a RS should be created
/home/runner/work/ramen/ramen/internal/controller/volsync/vshandler_test.go:689

  Timeline >>
  2025-02-05T17:41:21.213Z	INFO	Reconciling RS	{"rsSpec": {"protectedPVC":{"namespace":"vh-5jmvz","name":"mytestpvc","protectedByVolSync":true,"storageID":{"id":""},"replicationID":{"id":""},"storageClassName":"test.storageclass","accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"3Gi"}}}}, "runFinalSync": false}
  2025-02-05T17:41:21.213Z	INFO	Secret exists	{"secretName": "dummycm-owner-fxfxm-vs-secret"}
  2025-02-05T17:41:21.215Z	INFO	ownerRef added to object	{"obj": "Secret/dummycm-owner-fxfxm-vs-secret"}
  2025-02-05T17:41:21.215Z	DEBUG	VolSync secret validated	{"secret name": "dummycm-owner-fxfxm-vs-secret"}
  2025-02-05T17:41:21.215Z	INFO	Fetching VolumeSnapshotClass	{"labelSelector": {}}
  2025-02-05T17:41:21.215Z	INFO	ReplicationSource not found, proceeding with setup
  2025-02-05T17:41:21.217Z	DEBUG	ReplicationSource createOrUpdate Complete	{"rsSpec": {"protectedPVC":{"namespace":"vh-5jmvz","name":"mytestpvc","protectedByVolSync":true,"storageID":{"id":""},"replicationID":{"id":""},"storageClassName":"test.storageclass","accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"3Gi"}}}}, "runFinalSync": false, "op": "created"}
  2025-02-05T17:41:21.217Z	DEBUG	ReplicationSource Reconcile Complete	{"rsSpec": {"protectedPVC":{"namespace":"vh-5jmvz","name":"mytestpvc","protectedByVolSync":true,"storageID":{"id":""},"replicationID":{"id":""},"storageClassName":"test.storageclass","accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"3Gi"}}}}, "runFinalSync": false}
  [FAILED] in [It] - /home/runner/work/ramen/ramen/internal/controller/volsync/vshandler_test.go:701 @ 02/05/25 17:41:21.217
  << Timeline

  [FAILED] Failed after 0.000s.
  Expected
      <*errors.StatusError | 0xc000e8c320>: 
      ReplicationSource.volsync.backube "mytestpvc" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "ReplicationSource.volsync.backube \"mytestpvc\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "mytestpvc",
                  Group: "volsync.backube",
                  Kind: "ReplicationSource",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  to be nil
  In [It] at: /home/runner/work/ramen/ramen/internal/controller/volsync/vshandler_test.go:701 @ 02/05/25 17:41:21.217
------------------------------
••••••••••••••••••••••••••••••••••••••••••••W0205 17:41:31.[80](https://github.com/RamenDR/ramen/actions/runs/13154707691/job/36737147860?pr=1805#step:4:81)3908   14603 reflector.go:484] pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/reflector.go:243: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
W0205 17:41:31.803909   14603 reflector.go:484] pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/reflector.go:243: watch of *v1.PlacementRule ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
W0205 17:41:31.803950   14603 reflector.go:484] pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/reflector.go:243: watch of *v1.Policy ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding


Summarizing 1 Failure:
  [FAIL] VolSync_Handler Reconcile ReplicationSource When reconciling RSSpec When the psk secret for volsync exists (will be pushed down by drpc from hub When no running pod is mounting the PVC to be protected [It] Should return a replication source and a RS should be created
  /home/runner/work/ramen/ramen/internal/controller/volsync/vshandler_test.go:701
```

### PR DESCRIPTION
**Pull request by pruthvitd**
Fix for UT failure.

Individual test has been executed with a repeat count of 10 times and this has passed, result has been pasted here for reference:
```
# ginkgo -focus="When no running pod is mounting the PVC to be protected" -repeat=10
:
:
All tests passed...
This was attempt 10 of 11.
Running Suite: Volsync Suite - /root/DR/ut-fix/ramen/internal/controller/volsync
================================================================================
Random Seed: 1739818202

Will run 1 of 56 specs
SSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Ran 1 of 56 Specs in 11.563 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 55 Skipped
PASS

Ginkgo ran 1 suite in 2m13.075674648s
Test Suite Passed
```

Fixes #1812
There could be intermittent failures due to #1835, which was prevalent prior to this fix.

### CODE REVIEW

File: internal/controller/volsync/vshandler_test.go [hunk 1]
```diff
@@ -689,16 +689,20 @@ var _ = Describe("VolSync_Handler", func() {
...
-						Expect(rs).ToNot(BeNil())
+						Eventually(func() error {
+							finalSyncCompl, rs, err := vsHandler.ReconcileRS(rsSpec, false)
+							if err != nil || finalSyncCompl == true || rs == nil {
+								return err
+							}
 
-						// ReconcileRS should have created the replication source - since the secret isn't there
-						Consistently(func() error {
+							return nil
```
Comment (nirs) [inline internal/controller/volsync/vshandler_test.go:698]: This code is confusing - it looks like we return an error, but err may be nil. You to look at it carefully to understand what the code is doing, and maybe check the implementation of ReconcileRS.

I'm not sure what Eventually is doing, is it waiting until the function returns nil?  If this is the case, eventually will finish when:

- err == nil
- finalSyncCompl == true (assuming err is always nil in this case)
- finalSyncCompl == false && rs == nil (assuming that err is always nil in this case)

Based on the previous code, this should be something like:

```go
Eventually(func() error {
    finalSyncCompl, rs, err := vsHandler.ReconcileRS(rsSpec, false)
	if err != nil {
	    return err
    }

    if finalSyncCompl != true {
        return errors.New("final sync did not complete")
    }

    if rs != nil {
        return fmt.Errorf("non nil rs: %v", rs)
    }

    return nil
}
```

Since this is very verbose, it should move to a helper function like waitForFinalSyncCompletion().

**Review by nirs — COMMENTED** [review]
Nice to see this flaky test fixed!

**Comment by nirs** [comment]
@pruthvitd I fixed the pr message to link this pr to the issues using the standard `Fixes #N` trailers. This way when we merge this PR the issues will be closed automatically.

I'm not sure how this fixes #1835, it seems the race remains with this change.

File: internal/controller/volsync/vshandler_test.go (hunk 1 above)
Comment (pruthvitd) [reply internal/controller/volsync/vshandler_test.go:698]: @nirs 
Scenario being tested:
1. There is a PVC.
2. User wishes to protect the application to which this PVC belong to, hence creates DRPC for this app. 
3. The behavior of the application is PVC will be mounted to the POD only for few mins/secs per day.

With the fix DFBUGS-580, Ramen will create replicationsource for the PVC irrespective of it being mounted on any running pod. Before  the fix, creation of RS was skipped if PVC is not mounted to active POD.
 
4. In the current UT mock-up scenario, PVC is not mounted to active POD. 

The expected behavior here is, upon VSHandler reconcilation, RS should be created. Validation of RS creation is being done in these steps.

The fix added is to wait for the Replication Source creation within the eventually block. And Replication Source object should consistently available.

Note the environment for this particular test is being created in the previous test and the same environment is being carried forward for the next test.

**Comment by pruthvitd** [comment]
> @pruthvitd I fixed the pr message to link this pr to the issues using the standard `Fixes #N` trailers. This way when we merge this PR the issues will be closed automatically.
> 
> I'm not sure how this fixes #1835, it seems the race remains with this change.

Thanks for adding the links.

Yes this fix will not resolve the #1835 issue, instead we will continue see flaky UT.

File: internal/controller/volsync/vshandler_test.go [hunk 2]
```diff
@@ -689,12 +689,20 @@ var _ = Describe("VolSync_Handler", func() {
 					It("Should return a replication source and a RS should be created", func() {
 						// Run another reconcile - we have the psk secret now but the pvc is not in use by
 						// a running pod
+
+						var err error
 						finalSyncCompl, rs, err := vsHandler.ReconcileRS(rsSpec, false)
 						Expect(err).ToNot(HaveOccurred())
 						Expect(finalSyncCompl).To(BeFalse())
 						Expect(rs).ToNot(BeNil())
```
Comment (nirs) [inline internal/controller/volsync/vshandler_test.go:697]: In a the previous version you ran vsHandler.ReconcileRS(rsSpec, false) multiple times until it succeeded or timed out. Why did you change this in this version?

File: internal/controller/volsync/vshandler_test.go [hunk 3]
```diff
@@ -689,12 +689,20 @@ var _ = Describe("VolSync_Handler", func() {
...
 
-						// ReconcileRS should have created the replication source - since the secret isn't there
+						// Ensure replication source is created
```
Comment (nirs) [inline internal/controller/volsync/vshandler_test.go:699]: Why did you change the comment?

File: internal/controller/volsync/vshandler_test.go [hunk 4]
```diff
@@ -689,12 +689,20 @@ var _ = Describe("VolSync_Handler", func() {
...
+						Eventually(func() error {
+							return k8sClient.Get(ctx,
+								types.NamespacedName{Name: rsSpec.ProtectedPVC.Name, Namespace: testNamespace.GetName()}, createdRS)
+						}, maxWait, interval).Should(Succeed())
```
Comment (nirs) [inline internal/controller/volsync/vshandler_test.go:703]: This gets volsyncv1alpha1.ReplicationSource, but we already verifed in line 697 that we a non-nil rs:

```go
Expect(rs).ToNot(BeNil())
```

So It seems that this code is pointless, since we already have the resource.

I think what we are missing in this pr is explanation of the issue(s) we are trying to fix. Why the test fails randomly? We may have many reason, but none is explained in the commit or pr message.

Lets start by understanding why the code fails. Based on this understanding we can evaludate the suggested fix.

**Review by nirs — COMMENTED** [review]
You change the fix, but the pr message is showing the results of a test run. Is this run relevant now? did run it again locally with the new version?

**Comment by nirs** [comment]
> # ginkgo -focus="When no running pod is mounting the PVC to be protected" -repeat=10

Can you share the complete command use for testing this, and the output of the command before the fix?

This may help to understand the root cause(s) for the random failure.

File: internal/controller/volsync/vshandler_test.go (hunk 3 above)
Comment (pruthvitd) [reply internal/controller/volsync/vshandler_test.go:699]: PSKsecret is created in the previous testcase, hence the comment is incorrect.

File: internal/controller/volsync/vshandler_test.go [hunk 5]
```diff
@@ -689,12 +689,20 @@ var _ = Describe("VolSync_Handler", func() {
 					It("Should return a replication source and a RS should be created", func() {
 						// Run another reconcile - we have the psk secret now but the pvc is not in use by
 						// a running pod
+
+						var err error
```
Comment (nirs) [inline internal/controller/volsync/vshandler_test.go:693]: This should not be needed for the change.

**Review by nirs — COMMENTED** [review]
The issue seems to be a caching issue:

1. We call a function that created a resource
2. k8sclient.Get() for the same resource returns NotFound

This may be caching issue in the k8sclient, or the api server retuning cached results. If we call Get mulltiple times it will eventually return the resource.

If we look in other tests, this code is full with eventually calls after creating a resource, but this test did not have this eventually call added by this change.

Looking at git history, this code was checking that the rs was *not* created for 3 years, added in:
https://github.com/nirs/ramen/commit/4c757dc12de2d345e804f64dc85c91d4e3f05d83

When we fixed the code to ignore pvc status and create rs in all cases in:
https://github.com/nirs/ramen/commit/a896bb1fcc680dd2c8fb8ec66366cf8c46bbb1b1

The change modified the code to expect non-nil result. This works most of the time but fails randomly without the eventually call.

File: internal/controller/volsync/vshandler_test.go [hunk 6]
```diff
@@ -689,12 +689,19 @@ var _ = Describe("VolSync_Handler", func() {
 					It("Should return a replication source and a RS should be created", func() {
 						// Run another reconcile - we have the psk secret now but the pvc is not in use by
 						// a running pod
+
```
[the remark this answers is not in the document]
Comment (pruthvitd) [reply internal/controller/volsync/vshandler_test.go]: Updated.

**Review by rakeshgm — APPROVED** [review]
