### PR TITLE
e2e: add retry logic for namespace annotation

### LINKED ISSUE #1962: e2e: add retry when annotating namespace
On openshift rdr cluster, after creating namespaces on managed clusters addNamespaceAnnotationForVolSync fails with:

```
2025-03-11T12:29:56.472+0530	ERROR	disapp-deploy-rbd-busybox	Failed to deploy workload: Operation cannot be fulfilled on namespaces "e2e-disapp-deploy-rbd-busybox": the object has been modified; please apply your changes to the latest version and try again
2025-03-11T12:29:56.479+0530	ERROR	disapp-deploy-cephfs-busybox	Failed to deploy workload: Operation cannot be fulfilled on namespaces "e2e-disapp-deploy-cephfs-busybox": the object has been modified; please apply your changes to the latest version and try again
```

With issue  #1919 fixed on ocp clusters by not annotating namespaces. This issue can be still hit in kubernetes clusters sometime. So we need to fix by adding retry while annotating namespace.

### PR DESCRIPTION
**Pull request by parikshithb**
Add RetryOnConflict to handle annotation for namespaces. This ensures conflicts are retried if the namespace object is modified while trying to annotate.

Fixes #1962

### CODE REVIEW

File: e2e/util/namespace.go [hunk 1]
```diff
@@ -105,26 +106,31 @@ func CreateNamespaceAndAddAnnotation(env *types.Env, namespace string, log *zap.
 
 func addNamespaceAnnotationForVolSync(cluster types.Cluster, namespace string, log *zap.SugaredLogger) error {
 	key := k8stypes.NamespacedName{Name: namespace}
-	objNs := &corev1.Namespace{}
 
-	if err := cluster.Client.Get(context.Background(), key, objNs); err != nil {
-		return err
-	}
+	err := retry.RetryOnConflict(retry.DefaultBackoff, func() error {
```
Comment (nirs) [inline e2e/util/namespace.go:110]: We don't need the temporary error variable, we can do:

    key := ...
    
    return retry.RetryOnConflict(retry.DefaultBackoff, func() error {
        ...
    })

**Review by nirs — COMMENTED** [review]
Looks good, can be simplified a little bit.
