### PR TITLE
Sync directly to the App PVC and save crash-consistent snapshot at de…

### LINKED ISSUE #665: [Ramen/VolSync] Save the last known good snapshot when using copyMethod Direct
PR #651 added the ability to sync directly to the Application PVC. That change does not leave behind a good snapshot to go back to in case the Application PVC is not in a good state after that failover is complete.

In this task, the last known snapshot will always be left around, and it won't be deleted until the workload is deleted.

### PR DESCRIPTION
**Pull request by BenamarMk**
Set up VolSync to save the last known good snapshot at the destination. This snapshot is replaced with a newer one every time a successful sync is complete. When the Application is failed over or relocated, this last snapshot will be retained for as long as the workload is deployed. Here is an example of what happens on initial deployment, failover, relocation, failover again, and then the workload is undeployed. Let's assume we have 2 clusters [Cp, Cf].
Cp is the preferred cluster, and Cf is the failover cluster. Sx represents the snapshot retained:

Initial Deployment
------------------
Cp=
Cf=S1 after every successful sync a new snapshot is taken and the old one is deleted.

Failover to Cf
-------------
Cp=S2 after every successful sync a new snapshot is taken and the old one is deleted.
Cf=S1

Relocate
---------
Cp=S2
Cf=S1,S3 in this scenario S1 is saved forever, but S3 is refreshed as above

Failover
--------
Cp=S2,S4 in this scenario S2 is saved forever, but S4 is refreshed as above Cf=S1,S3

Updeploy the workload
-----------------------
Cp=
Cf=

Fixes #665 

Signed-off-by: Benamar Mekhissi <bmekhiss@redhat.com>

### CODE REVIEW

**Review by ShyamsundarR — APPROVED** [review]

**Comment by ShyamsundarR** [comment]
@tesshuflower can you also take a quick look, thanks!

File: controllers/volsync/vshandler.go [hunk 1]
```diff
@@ -931,21 +919,37 @@ func (v *VSHandler) validateSnapshotAndEnsurePVC(rdSpec ramendrv1alpha1.VolSyncR
...
+			restoreSize = snap.Status.RestoreSize
+		}
+
+		_, err := v.ensurePVCFromSnapshot(rdSpec, snapshotRef, restoreSize)
+		if err != nil {
+			return err
+		}
 	}
 
 	// Add ownerRef on snapshot pointing to the pvc - if/when the PVC gets cleaned up, then GC can cleanup the snap
```
Comment (tesshuflower) [inline controllers/volsync/vshandler.go:951]: Do you mind updating this comment?  Just so it's clear that we're making the vrg the owner of the snapshot now instead of the pvc

Comment (BenamarMk) [reply controllers/volsync/vshandler.go]: Updated

**Comment by BenamarMk** [comment]
I made one more commit [here](https://github.com/RamenDR/ramen/pull/670/commits/e63092dcc1235bd69be1f1e1c7da544d9dc77d05) 
Please take a look. The reason for that commit is that on initial deployment, the secondary VRG will not have any of the conditions set.  The DataReady will never be found and we never set the vrg.Status.State to `Secondary`.  Not harmful for the VolSync when secondary, It is mostly a display issue, but correcting it, nevertheless.

**Review by tesshuflower — APPROVED** [review]
/lgtm
