### PR TITLE
Delete VR before PVC deletion

### LINKED ISSUE #52: order of VR protection finalizer removal for pvc and VR deletion
Currently, the VolumeReplicationGroup controller does applies finalizers to pvc when it creates a VolumeReplication resource for
each pvc being disaster protected. This ensures that pvc cannot be deleted until the VolumeReplication resource is present and the finalizer applied to pvc is removed. When VolumeReplication resource has to be deleted, VolumeReplicationGroup controller does the below things in the order mentioned.

1) prepare pvc for deletion
   - This includes things such as removing the VolumeReplication protection finalizer from the corresponding pvc.
   - Removing annotations on the pvc that were maintained by VolumeReplicationGroup.
   
2) Deleting the VolumeReplication resource.

However, there is a chance that after the 1st step, deletion of the VolumeReplication resource fails for some reason. This leads to VolumeReplicationGroup controller requeing for another reconcile loop. And by the time a new reconcile loop is started, there is a chance that the corresponding pvc got deleted (since finalizers were removed from pvc). This means in the new reconcile loop, VolumeReplicationGroup would not be knowing about the pvc that got deleted. Thus this means that, the VolumeReplication resource that could not be deleted will not get a chance to be deleted (as its corresponding pvc got deleted. And VolumeReplicationGroup gets to VolumeReplication resource through the pvc). 

This can lead to a leak of VolumeReplication resources in the system. And if the async replication setup on the PVs is intact due to VolumeReplication resource being present (can happen when the storageclass has its DeletionPolicy set to Retain, which means deletion of pvc does not cause deletion of PV), this can also impact the garbage collection of PVs.

### PR DESCRIPTION
**Pull request by ShyamsundarR**
We had a leak in VR if the reconcile was
interrupted, this is fixed by deleting the VR before
marking the PVC as no longer protected.

This helps with finalizer updates, when there are races
to finalize VRG due to PVC events, and the state fails
in between.

We also ensure VR is in the desired state before deleting
the same, and finalizing the VRG, to leave the system in
an overall desired and consistent state.

Also, corrects S3 object deletion to delete all PVs inside the
PVC bucket.

Fixes #52

Signed-off-by: Shyamsundar Ranganathan <srangana@redhat.com>

### CODE REVIEW

File: controllers/volumereplicationgroup_controller.go [hunk 1]
```diff
@@ -665,15 +661,17 @@ func (v *VRGInstance) reconcileVRForDeletion(pvc *corev1.PersistentVolumeClaim,
 		return requeue
 	}
 
-	if err := v.preparePVCForVRDeletion(pvc, log); err != nil {
-		log.Info("Requeuing due to failure in preparing PersistentVolumeClaim for VolumeReplication deletion",
+	// Deleting VR first may end-up recreating the VR if reconcile for this PVC is interrupted, but that is better than
```
Comment (BenamarMk) [inline controllers/volumereplicationgroup_controller.go:664]: Question: If the reconcile for this PVC is interrupted, why do you think it will end up recreating the VR? isn't it protected by [this line ](https://github.com/RamenDR/ramen/blob/400fddb4c913a1e9f53af02d51a71fe5fa51ce53/controllers/volumereplicationgroup_controller.go#L377). IOW, the VR should never be created if the VRG is being deleted.  So as far as I see, there is no issue here.

**Review by BenamarMk — APPROVED** [review]
LGTM. I only have one question.

File: controllers/volumereplicationgroup_controller.go (hunk 1 above)
Comment (BenamarMk) [reply controllers/volumereplicationgroup_controller.go:664]: Oh, I think it is [this line](https://github.com/RamenDR/ramen/blob/400fddb4c913a1e9f53af02d51a71fe5fa51ce53/controllers/volumereplicationgroup_controller.go#L661). Ignore my comment then.

Comment (ShyamsundarR) [reply controllers/volumereplicationgroup_controller.go:664]: :) ack! I was just creating this comment... processForDeletion -> reconcileVRsForDeletion -> reconcileVRForDeletion -> processVRAsPrimary/Secondary -> createOrUpdateVR...

**Review by raghavendrabhat — APPROVED** [review]

File: controllers/volumereplicationgroup_controller.go [hunk 2]
```diff
@@ -617,14 +617,10 @@ func (v *VRGInstance) reconcileVRsForDeletion() bool {
...
 		log := v.log.WithValues("pvc", pvcNamespacedName.String())
 
-		requeueResult, skip := v.preparePVCForVRProtection(pvc, log)
-		if requeueResult {
-			requeue = true
-
-			continue
-		}
+		// Skip unprotected PVCs during delete
+		if pvc.Annotations[pvcVRAnnotationProtectedKey] != pvcVRAnnotationProtectedValue {
```
Comment (ShyamsundarR) [inline controllers/volumereplicationgroup_controller.go:621]: Having some doubts on what to check to check to ignore a PVC, I think it should be the finalizer and not the annotation here. (@BenamarMk @raghavendrabhat )

Comment (BenamarMk) [reply controllers/volumereplicationgroup_controller.go:621]: So the Annotation guarantees that even the PV metadata has been uploaded to s3.  Whereas the Finalizer doesn't guarantee that. However, it's error-prone if we use the annotation to check for VRProtection.  Because, if we fail to upload to s3 store, then the VRAnnotation will not be set. Hence, we skip reconciling VR for deletion.  so I think it is a good catch @ShyamsundarR.

**Comment by ShyamsundarR** [comment]
@BenamarMk and @raghavendrabhat This PR is now dependent on #218 

The change to logic here is to keep processing PVCs that are marked with finalizers, but ensure VR is in the desired state before deletion. To prevent resource leaks in the storage system.

Also addressed the S3 deletion issue here, but we can decide if we want that in #218 and removed from here.

File: controllers/volumereplicationgroup_controller.go [hunk 3]
```diff
@@ -61,7 +61,7 @@ type PVUploader interface {
 }
 
 type PVDeleter interface {
-	DeletePV(v interface{}, s3ProfileName string, pvc *corev1.PersistentVolumeClaim) error
+	DeletePV(v interface{}, s3ProfileName string) error
```
Comment (BenamarMk) [inline controllers/volumereplicationgroup_controller.go:64]: (nit) DeletePV name should probably change to DeletePVs now that it is deleting a bunch.

**Review by BenamarMk — APPROVED** [review]
LGTM. We can merge it as is.  I can simply close #218 once this is merged.

File: controllers/volumereplicationgroup_controller.go (hunk 3 above)
Comment (ShyamsundarR) [reply controllers/volumereplicationgroup_controller.go:64]: True.. will make this change.

**Comment by ShyamsundarR** [comment]
> LGTM. We can merge it as is. I can simply close #218 once this is merged.

Hmmm. that works as well.. as we have commit history with the right names.

File: controllers/volumereplicationgroup_controller.go (hunk 3 above)
Comment (ShyamsundarR) [reply controllers/volumereplicationgroup_controller.go]: done!

Comment (raghavendrabhat) [reply controllers/volumereplicationgroup_controller.go]: Should there be a function to handle deletion of an individual PV from S3 store?

Comment (BenamarMk) [reply controllers/volumereplicationgroup_controller.go]: I am not sure if necessary, but all the plumbing is there, so if needed, we'll add one.

Comment (raghavendrabhat) [reply controllers/volumereplicationgroup_controller.go]: ACK

**Review by raghavendrabhat — APPROVED** [review]
LGTM
