### PR TITLE
vrg: synchronize map writes

### LINKED ISSUE #2048: fatal error: concurrent map writes while protecting kubeobjects - ramen-operator pod crash
Observed this crash on OCP downstream setup:
```
2025-05-20T15:47:11.324Z	INFO	controllers.VolumeReplicationGroup	controller/vrg_vrgobject.go:58	VRG Kube object protected	{"VolumeReplicationGroup": {"name":"rbd-sub-busybox5-custom-sc-placement-1-drpc","namespace":"busybox-workloads-5"}, "rid": "98d59a02-47fc-4e27-a339-abef6f94c91e", "State": "primary", "profile": "s3profile-amagrawa-2-12m-ocs-storagecluster"}
fatal error: concurrent map writes

goroutine 720 [running]:
github.com/ramendr/ramen/internal/controller.(*VRGInstance).vrgObjectProtectThrottled(0xc0007ccb48, 0xc0007ccd48, 0x22831a8, 0x22831b0)
	/src/remote_source/app/internal/controller/vrg_vrgobject.go:60 +0x325
github.com/ramendr/ramen/internal/controller.(*VRGInstance).vrgObjectProtect(0xc0007ccb48, 0xc0007ccd48)
	/src/remote_source/app/internal/controller/vrg_vrgobject.go:27 +0x157
github.com/ramendr/ramen/internal/controller.(*VRGInstance).processAsPrimary(0xc0007ccb48)
	/src/remote_source/app/internal/controller/volumereplicationgroup_controller.go:1346 +0x425
github.com/ramendr/ramen/internal/controller.(*VRGInstance).processVRG(0xc0007ccb48)
	/src/remote_source/app/internal/controller/volumereplicationgroup_controller.go:597 +0x6ed
github.com/ramendr/ramen/internal/controller.(*VolumeReplicationGroupReconciler).Reconcile(0xc00079af00, {0x25a4658, 0xc0012decf0}, {{{0xc00564a4b0, 0x13}, {0xc005e1e150, 0x2b}}})
	/src/remote_source/app/internal/controller/volumereplicationgroup_controller.go:470 +0xbd6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc0012dec60?, {0x25a4658?, 0xc0012decf0?}, {{{0xc00564a4b0?, 0x0?}, {0xc005e1e150?, 0x0?}}})
	/cachi2/output/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:116 +0xbf
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x25b6c60, {0x25a4690, 0xc0007f12c0}, {{{0xc00564a4b0, 0x13}, {0xc005e1e150, 0x2b}}})
	/cachi2/output/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:303 +0x398
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x25b6c60, {0x25a4690, 0xc0007f12c0})
	/cachi2/output/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263 +0x230
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()
	/cachi2/output/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 48
	/cachi2/output/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:220 +0x490

```

### PR DESCRIPTION
**Pull request by asn1809**
Fixes #2048. Issue was seen when concurrent writes to the map was done. To solve the same, sync.Map is being made use of, which is thread safe.

### CODE REVIEW

File: internal/controller/vrg_vrgobject.go [hunk 1]
```diff
@@ -4,20 +4,22 @@
...
+	"sync"
+
 	ramen "github.com/ramendr/ramen/api/v1alpha1"
 	"github.com/ramendr/ramen/internal/controller/util"
 	corev1 "k8s.io/api/core/v1"
 	ctrl "sigs.k8s.io/controller-runtime"
 )
 
-var vrgLastUploadVersion = map[string]string{}
+var vrgLastUploadVersion sync.Map
```
Comment (nirs) [inline internal/controller/vrg_vrgobject.go:15]: sync.Map is recommended only for special cases:
> The Map type is specialized. Most code should use a plain Go map instead, with separate locking or coordination, for better type safety and to make it easier to maintain other invariants along with the map content.

> The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate [Mutex](https://pkg.go.dev/sync#Mutex) or [RWMutex](https://pkg.go.dev/sync#RWMutex).

See https://pkg.go.dev/sync#Map

If we don't use the special use case, we should use a lock to synchronize access to the map.

**Review by ShyamsundarR — APPROVED** [review]
