### PR TITLE
e2e: add kubeconfig to env and replace with context

### LINKED ISSUE #1920: e2e: discoverd app test failures during deploy and undeploy
On openshift rdr cluster, `TestDR/disapp-deploy-rbd-busybox` and `TestDR/disapp-deploy-cephfs-busybox` fails with non existing cluster context. Since we create create and delete discovered apps like:
```
	cmd := exec.Command("kubectl", "apply", "-k", tempDir, "-n", appNamespace,
		"--context", drpolicy.Spec.DRClusters[0], "--timeout=5m")

	cmd := exec.Command("kubectl", "delete", "-k", tempDir, "-n", namespace,
		"--context", cluster, "--timeout=5m", "--ignore-not-found=true")
```

Failures: 

1. deploy:
```
2025-03-11T13:19:03.687+0530	ERROR	disapp-deploy-rbd-busybox	Failed to undeploy workload: exit status 1: stdout="" stderr="error: context \"sraghave-mc1\" does not exist\n"
2025-03-11T13:19:03.687+0530	ERROR	disapp-deploy-cephfs-busybox	Failed to undeploy workload: exit status 1: stdout="" stderr="error: context \"sraghave-mc1\" does not exist\n"
```

2. undeploy:
```
2025-03-11T13:19:03.687+0530	ERROR	disapp-deploy-rbd-busybox	Failed to undeploy workload: exit status 1: stdout="" stderr="error: context \"sraghave-mc1\" does not exist\n"
2025-03-11T13:19:03.687+0530	ERROR	disapp-deploy-cephfs-busybox	Failed to undeploy workload: exit status 1: stdout="" stderr="error: context \"sraghave-mc1\" does not exist\n"
```

### PR DESCRIPTION
**Pull request by parikshithb**
This change adds kubeconfig field to Cluster enabling access from env. Using the kubeconfig from env, replaced --context with --kubeconfig for kubectl commands in discovered app created and delete since cluster contexts does not exist by default on openshift clusters.

Tested disapp-rbd on openshift qe cluster:
[ramen-e2e.log](https://github.com/user-attachments/files/19248161/ramen-e2e.log)

Fixes #1920

### CODE REVIEW

File: e2e/dractions/disapp.go [hunk 1]
```diff
@@ -129,8 +129,13 @@ func failoverRelocateDiscoveredApps(
 		return err
 	}
 
+	currentDRCluster, err := env.GetEnvCluster(ctx, currentCluster)
```
Comment (nirs) [inline e2e/dractions/disapp.go:132]: currentDRCluster is not the best name. The best name is currentCluster but it is used for the cluster names. Can we pass cluster objects instead of strings to this function?

A smaller change would be to rename the arguments to currentClusterName and targetClusterName.

File: e2e/dractions/disapp.go [hunk 2]
```diff
@@ -142,10 +147,10 @@ func failoverRelocateDiscoveredApps(
 		return err
 	}
 
-	drCluster, err := env.GetEnvCluster(ctx, targetCluster)
+	targetDRCluster, err := env.GetEnvCluster(ctx, targetCluster)
```
Comment (nirs) [inline e2e/dractions/disapp.go:150]: Same for this name.

**Comment by nirs** [comment]
@parikshithb please rebase on main, #1923 was merged

**Comment by nirs** [comment]
> Based on #1929

Do we have a reason to base it on the other patch? Previously it was needed because of #1916.

**Comment by parikshithb** [comment]
> > Based on #1929
> 
> Do we have a reason to base it on the other patch? Previously it was needed because of #1916.

I wanted to run e2e tests with all fixes on qe env using a branch, so.

**Review by nirs — COMMENTED** [review]
@parikshithb please rebase

**Review by nirs — APPROVED** [review]
Looks goods, conflicts with #1941 but this seems ready now.

**Comment by nirs** [comment]
@parikshithb please rebase

**Review by nirs — APPROVED** [review]
