### PR TITLE
e2e: Fix improper use of formatting

### LINKED ISSUE #1618: e2e: Improper use of error formatting
We have many instances like this:

```go
fmt.Errorf("drpc " + drpcName + " is not ready yet before timeout, fail")
```

Should use:

```go
fmt.Errorf("drpc %q is not ready yet before timeout, fail", drpcName)
```

Notes: Use %q to get clear values in logs, and detect values with leading or trailing whitespace

### PR DESCRIPTION
**Pull request by alonsofabila-dev**
When using fmt.Errorf(), we don't need to format the message with
fmt.Sprintf().

Fixes #1618

### CODE REVIEW

File: e2e/dractions/retry.go [hunk 1]
```diff
@@ -46,7 +46,7 @@ func waitPlacementDecision(client client.Client, namespace string, placementName
 
 		if time.Since(startTime) > time.Second*time.Duration(util.Timeout) {
 			return "", fmt.Errorf(
-				"could not get placement decision for " + placementName + " before timeout, fail")
+				"could not get placement decision for %s before timeout, fail", placementName)
```
Comment (nirs) [inline e2e/dractions/retry.go:49]: Using %q will add quotes around the value, making it the log more clear, and revealing issues with leading or trailing whitespace in the value.

**Review by nirs — COMMENTED** [review]
Thansk @alonsofabila-dev!

Few issues:
- Use %q instead of %s
- No need to split to commits by file, you can squash the commits to single commit.
- Add this header to the commit message:

  ```
  Fixes: #1618
  ```

**Review by nirs — COMMENTED** [review]
One more thing - not clear what is the `(chore) ` prefix. Check recent commits for the style used in this project.

File: e2e/dractions/retry.go (hunk 1 above)
Comment (alonsofabila-dev) [reply e2e/dractions/retry.go:49]: should i change also the ones that already use %s to %q too?

Comment (nirs) [reply e2e/dractions/retry.go:49]: > should i change also the ones that already use %s to %q too?

This can be the next PR, lets focus now on fixing the logs that do not use the format properly.

Comment (alonsofabila-dev) [reply e2e/dractions/retry.go]: done

**Review by nirs — COMMENTED** [review]
The actual change look good now, but we have 3 commits for for the same logical change. We want to have a single commit in git history for this issue.

Replacing %s with %q can be considered a different change, and maybe it is better done for the entire e2e package. This will be more work since lot of code use string concatenation ("a " + b + " c") instead of formatting which makes it harder to quote values.

To keep this PR simple and complete it quickly, lets remove the last commit and work on quoting later.

The first 2 commits should be squashed using git rebase. If you never did this see https://github.com/RamenDR/ramen/issues/1623.

The commit message have headers (like Signed-off-by: alonso fabila <jorge.fabila@encora.com>). We want another header with (Fixes: #1618). You add the header as the commit message title in the last commit.

**Comment by alonsofabila-dev** [comment]
donde

**Comment by nirs** [comment]
@alonsofabila-dev thanks for the update. If you don't mind I'll fix the commit message myself.

**Comment by nirs** [comment]
@alonsofabila-dev I push another version with some minor changes:
- Fix the another instance that you change %s to %q but did not remove the fmt.Sprintf

```diff
diff --git a/e2e/dractions/retry.go b/e2e/dractions/retry.go
index dddcd38e..cb4a285f 100644
--- a/e2e/dractions/retry.go
+++ b/e2e/dractions/retry.go
@@ -206,7 +206,7 @@ func waitDRPCDeleted(client client.Client, namespace string, name string) error
                }
 
                if time.Since(startTime) > time.Second*time.Duration(util.Timeout) {
-                       return fmt.Errorf(fmt.Sprintf("drpc %q is not deleted yet before timeout, fail", name))
+                       return fmt.Errorf("drpc %q is not deleted yet before timeout, fail", name)
                }
 
                time.Sleep(time.Second * time.Duration(util.TimeInterval))
```

2. Fix the commit message to be in the standard format
3. Fix the PR message by copying the commit message

**Comment by nirs** [comment]
@alonsofabila-dev git grep show other instances that you did not fix:

```
% git grep 'fmt.Errorf(fmt.Sprintf'
deployers/retry.go:                     return fmt.Errorf(fmt.Sprintf("subscription %s status is not %s yet before timeout", name, phase))
deployers/retry.go:                     return fmt.Errorf(fmt.Sprintf("workload %s is not ready yet before timeout of %v",
dractions/retry.go:                     return fmt.Errorf(fmt.Sprintf(
dractions/retry.go:                     return fmt.Errorf(fmt.Sprintf("drpc %s progression is not %s yet before timeout of %v",
```

**Comment by alonsofabila-dev** [comment]
done

**Comment by nirs** [comment]
@alonsofabila-dev please rebase on main, some of the changes already fixed by another pr merged just now.

**Comment by nirs** [comment]
@alonsofabila-dev I asked to rebase on main, but you merged it - this is not the same. We want to have clean linear history in git without merge commits. The way to update your PR is to use:

```
git checkout main
git pull upstream main
git checkout your-pr-branch
git rebase main
(fix possible conflicts)
git push -f
```

This should be done each time you push changes, to make sure your change is tested on top of latest version.

**Comment by alonsofabila-dev** [comment]
sorry for my mistake, I have now done as you mentioned.

**Comment by nirs** [comment]
@alonsofabila-dev You rebased, but you had to "pick" only your commit. I clean up and resolved the conflicts.

**Comment by alonsofabila-dev** [comment]
thanks

**Review by nirs — APPROVED** [review]
