### PR TITLE
Fix waiting until placement decision is available

### LINKED ISSUE #1562: e2e flake: starting test fails with panic: runtime error: index out of range [0] with length 0
I see this failure many times when running the tests in the first time with a new environment. Typically the next tries work. Looks like incorrect setup that fixes itself on the next run since a resource was created on the cluster in the failed attempt.

We can add a retry for the entire test suite, it is faster to rerun the tests than to create a new environment.

```
=== RUN   TestSuites/Exhaustive/Deploy-rbd#01/Appset
2024-09-16T22:16:15.056+0530	INFO	deployers/applicationset.go:17	enter Deploy appset-deploy-cephfs-busybox
=== PAUSE TestSuites/Exhaustive/Deploy-rbd#01/Appset
=== CONT  TestSuites/Exhaustive/Deploy-rbd#01/Appset
=== RUN   TestSuites/Exhaustive/Deploy-rbd#01/Appset/Deploy
=== RUN   TestSuites/Exhaustive/Deploy-rbd/Subscr
2024-09-16T22:16:15.056+0530	INFO	deployers/applicationset.go:17	enter Deploy appset-deploy-rbd-busybox
=== PAUSE TestSuites/Exhaustive/Deploy-rbd/Subscr
=== RUN   TestSuites/Exhaustive/Deploy-cephfs/Subscr/Deploy
2024-09-16T22:16:15.056+0530	INFO	deployers/subscription.go:31	enter Deploy subscr-deploy-cephfs-busybox
=== PAUSE TestSuites/Exhaustive/Deploy-cephfs#02/Disapp
=== CONT  TestSuites/Exhaustive/Deploy-cephfs#02/Disapp
=== RUN   TestSuites/Exhaustive/Deploy-rbd#02/Disapp
=== CONT  TestSuites/Exhaustive/Deploy-rbd/Subscr
=== PAUSE TestSuites/Exhaustive/Deploy-rbd#02/Disapp
=== CONT  TestSuites/Exhaustive/Deploy-rbd#02/Disapp
=== RUN   TestSuites/Exhaustive/Deploy-rbd#02/Disapp/Deploy
2024-09-16T22:16:15.0[57](https://github.com/RamenDR/ramen/actions/runs/10887936359/job/30211267322#step:12:58)+0530	INFO	deployers/discoveredapps.go:24	enter Deploy disapp-deploy-rbd-busybox
=== RUN   TestSuites/Exhaustive/Deploy-rbd/Subscr/Deploy
=== NAME  TestSuites/Exhaustive/Deploy-cephfs#02/Disapp
    exhaustive_suite_test.go:93: Workload Deploy-cephfs not supported by deployer Disapp, skip test
2024-09-16T22:16:15.057+0530	INFO	deployers/subscription.go:31	enter Deploy subscr-deploy-rbd-busybox
=== RUN   TestSuites/Exhaustive/Deploy-cephfs#01/Appset/Enable
2024-09-16T22:16:16.920+0530	INFO	dractions/actions.go:38	enter EnableProtection appset-deploy-cephfs-busybox
=== RUN   TestSuites/Exhaustive/Deploy-rbd#01/Appset/Enable
2024-09-16T22:16:16.936+0530	INFO	dractions/actions.go:38	enter EnableProtection appset-deploy-rbd-busybox
2024-09-16T22:16:17.022+0530	INFO	util/crud.go:99	channel ramen-gitops is deleted
--- FAIL: TestSuites (2.99s)
    --- PASS: TestSuites/Validate (0.38s)
        --- PASS: TestSuites/Validate/CheckRamenHubOperatorStatus (0.32s)
        --- PASS: TestSuites/Validate/CheckRamenSpokeOperatorStatus (0.06s)
    --- FAIL: TestSuites/Exhaustive (2.35s)
        --- PASS: TestSuites/Exhaustive/Deploy-cephfs#02 (0.00s)
            --- SKIP: TestSuites/Exhaustive/Deploy-cephfs#02/Disapp (0.00s)
        --- FAIL: TestSuites/Exhaustive/Deploy-rbd#01 (1.92s)
            --- FAIL: TestSuites/Exhaustive/Deploy-rbd#01/Appset (1.92s)
                --- PASS: TestSuites/Exhaustive/Deploy-rbd#01/Appset/Deploy (1.88s)
                --- FAIL: TestSuites/Exhaustive/Deploy-rbd#01/Appset/Enable (0.04s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
```

### PR DESCRIPTION
**Pull request by nirs**
We cannot use the method we used in [drenv/test.lookup_cluster](https://github.com/RamenDR/ramen/blob/2886c647e9c465f5fe7a8665e53c37de002b6326/test/drenv/test.py#L204) since placement Satisfied condition is not set in discovered apps flows.

Simplify the code to wait until we have placement decisions status
contains non empty decisions list. 

Fixes: https://github.com/RamenDR/ramen/issues/1562

### CODE REVIEW

**Comment by nirs** [comment]
Needs more work, this seem to fail for discovered apps:

```
=== NAME  TestSuites/Exhaustive/Deploy-rbd#02/Disapp/Failover
    actions_test.go:42: timeout waiting until placement "disapp-deploy-rbd-busybox" is satisfied
=== NAME  TestSuites/Exhaustive/Deploy-rbd#02/Disapp
    exhaustive_suite_test.go:93: Failover failed
```

Maybe we need to wait util placement decision is created and have non empty decisions list.

File: e2e/dractions/retry.go [hunk 1]
```diff
@@ -15,38 +15,28 @@ import (
 	"sigs.k8s.io/controller-runtime/pkg/client"
 )
 
-// nolint:gocognit
-// return placementDecisionName, error
-func waitPlacementDecision(client client.Client, namespace string, placementName string,
-) (string, error) {
+// waitPlacementDecsision waits until we have placemnt desicion and return the placmenet decision object.
+func waitPlacmentDecision(client client.Client, namespace string, placementName string,
```
Comment (ELENAGER) [inline e2e/dractions/retry.go:19]: Typo: waitPlacementDecision

Comment (nirs) [reply e2e/dractions/retry.go]: I think I fixed all the typos, thanks for reviewing!

**Review by ELENAGER — APPROVED** [review]
LGTM

**Review by ShyamsundarR — APPROVED** [review]

**Comment by nirs** [comment]
Fixing the conflict...
