### PR TITLE
Wait when deleting a namespace                                                                                                                                  

### LINKED ISSUE #1620: e2e: -count=N does not work because channel namespace is terminating
Trying to run the same tests multiple times for evaluating test flakiness breaks because the channel is deleted during cleanup.

Ideally the flow will be:

1. global setup before all tests
2. run one or more tests count times
3. global teardown before existing

I'm not sure this is possible with -count=N.

If not possible and the channel need to be deleted, we mitigate this in several ways:

- Wait until the channel and the namespace are deleted during cleanup, so installing the channel again will not fail.
- Add a flag to skip the cleanup, to be used for special cases like -count=N
- Add flag to skip adding/removing the channel, it can be added manually
- Implement -count=N internally so we can control setup and teardown 

## Example run

```
% ./run.sh --config ../e2e.yaml -run TestSuites/Exhaustive/Deploy-cephfs/Subscr -count=2
Running tests...
2024-10-28T19:48:18.586+0200	INFO	e2e/main_test.go:41	Global setting	{"Timeout": 600}
2024-10-28T19:48:18.587+0200	INFO	e2e/main_test.go:42	Global setting	{"Retry Interval": 30}
=== RUN   TestSuites
2024-10-28T19:48:18.587+0200	INFO	e2e/main_test.go:57	TestSuites
=== RUN   TestSuites/Exhaustive
=== PAUSE TestSuites/Exhaustive
=== CONT  TestSuites/Exhaustive
2024-10-28T19:48:18.618+0200	INFO	util/crud.go:77	channel ramen-gitops is created
=== RUN   TestSuites/Exhaustive/Deploy-cephfs
=== PAUSE TestSuites/Exhaustive/Deploy-cephfs
=== RUN   TestSuites/Exhaustive/Deploy-cephfs#01
=== PAUSE TestSuites/Exhaustive/Deploy-cephfs#01
=== RUN   TestSuites/Exhaustive/Deploy-cephfs#02
=== PAUSE TestSuites/Exhaustive/Deploy-cephfs#02
=== CONT  TestSuites/Exhaustive/Deploy-cephfs
=== CONT  TestSuites/Exhaustive/Deploy-cephfs#02
=== CONT  TestSuites/Exhaustive/Deploy-cephfs#01
=== RUN   TestSuites/Exhaustive/Deploy-cephfs/Subscr
=== PAUSE TestSuites/Exhaustive/Deploy-cephfs/Subscr
=== CONT  TestSuites/Exhaustive/Deploy-cephfs/Subscr
=== RUN   TestSuites/Exhaustive/Deploy-cephfs/Subscr/Deploy
2024-10-28T19:48:18.619+0200	INFO	deployers/subscription.go:31	enter Deploy subscr-deploy-cephfs-busybox
2024-10-28T19:48:23.750+0200	INFO	deployers/retry.go:32	subscription subscr-deploy-cephfs-busybox phase is Propagated
=== RUN   TestSuites/Exhaustive/Deploy-cephfs/Subscr/Enable
2024-10-28T19:48:23.751+0200	INFO	dractions/actions.go:39	enter EnableProtection subscr-deploy-cephfs-busybox
2024-10-28T19:48:23.755+0200	INFO	dractions/actions.go:52	got clusterName dr1 from subscr-deploy-cephfs-busybox-decision-1
2024-10-28T19:48:23.755+0200	INFO	dractions/actions.go:54	update placement subscr-deploy-cephfs-busybox annotation
2024-10-28T19:48:23.762+0200	INFO	dractions/actions.go:73	create drpc subscr-deploy-cephfs-busybox
2024-10-28T19:51:23.842+0200	INFO	dractions/retry.go:57	drpc subscr-deploy-cephfs-busybox is ready
=== RUN   TestSuites/Exhaustive/Deploy-cephfs/Subscr/Failover
2024-10-28T19:51:23.843+0200	INFO	dractions/actions.go:115	enter Failover subscr-deploy-cephfs-busybox
2024-10-28T19:51:23.851+0200	INFO	dractions/retry.go:57	drpc subscr-deploy-cephfs-busybox is ready
2024-10-28T19:51:23.861+0200	INFO	dractions/actions.go:175	update drpc subscr-deploy-cephfs-busybox failover to dr2
2024-10-28T19:52:28.884+0200	INFO	dractions/retry.go:114	drpc subscr-deploy-cephfs-busybox phase is FailedOver
2024-10-28T19:53:58.901+0200	INFO	dractions/retry.go:57	drpc subscr-deploy-cephfs-busybox is ready
=== RUN   TestSuites/Exhaustive/Deploy-cephfs/Subscr/Relocate
2024-10-28T19:53:58.901+0200	INFO	dractions/actions.go:130	enter Relocate subscr-deploy-cephfs-busybox
2024-10-28T19:53:58.903+0200	INFO	dractions/retry.go:57	drpc subscr-deploy-cephfs-busybox is ready
2024-10-28T19:53:58.909+0200	INFO	dractions/actions.go:175	update drpc subscr-deploy-cephfs-busybox relocate to dr1
2024-10-28T19:56:33.939+0200	INFO	dractions/retry.go:114	drpc subscr-deploy-cephfs-busybox phase is Relocated
2024-10-28T19:57:03.947+0200	INFO	dractions/retry.go:57	drpc subscr-deploy-cephfs-busybox is ready
=== RUN   TestSuites/Exhaustive/Deploy-cephfs/Subscr/Disable
2024-10-28T19:57:03.947+0200	INFO	dractions/actions.go:99	enter DisableProtection subscr-deploy-cephfs-busybox
2024-10-28T19:57:03.947+0200	INFO	dractions/actions.go:104	delete drpc subscr-deploy-cephfs-busybox
2024-10-28T19:57:38.966+0200	INFO	dractions/retry.go:183	drpc subscr-deploy-cephfs-busybox is deleted
=== RUN   TestSuites/Exhaustive/Deploy-cephfs/Subscr/Undeploy
2024-10-28T19:57:38.966+0200	INFO	deployers/subscription.go:62	enter Undeploy subscr-deploy-cephfs-busybox
2024-10-28T19:57:39.009+0200	INFO	util/crud.go:99	channel ramen-gitops is deleted
--- PASS: TestSuites (0.00s)
    --- PASS: TestSuites/Exhaustive (0.06s)
        --- PASS: TestSuites/Exhaustive/Deploy-cephfs#02 (0.00s)
        --- PASS: TestSuites/Exhaustive/Deploy-cephfs#01 (0.00s)
        --- PASS: TestSuites/Exhaustive/Deploy-cephfs (0.00s)
            --- PASS: TestSuites/Exhaustive/Deploy-cephfs/Subscr (560.38s)
                --- PASS: TestSuites/Exhaustive/Deploy-cephfs/Subscr/Deploy (5.13s)
                --- PASS: TestSuites/Exhaustive/Deploy-cephfs/Subscr/Enable (180.09s)
                --- PASS: TestSuites/Exhaustive/Deploy-cephfs/Subscr/Failover (155.06s)
                --- PASS: TestSuites/Exhaustive/Deploy-cephfs/Subscr/Relocate (185.05s)
                --- PASS: TestSuites/Exhaustive/Deploy-cephfs/Subscr/Disable (35.01s)
                --- PASS: TestSuites/Exhaustive/Deploy-cephfs/Subscr/Undeploy (0.03s)
=== RUN   TestSuites
2024-10-28T19:57:39.027+0200	INFO	e2e/main_test.go:57	TestSuites
=== RUN   TestSuites/Exhaustive
=== PAUSE TestSuites/Exhaustive
=== CONT  TestSuites/Exhaustive
    main_test.go:64: failed to ensure channel: channels.apps.open-cluster-management.io "ramen-gitops" is forbidden: unable to create new content in namespace ramen-samples because it is being terminated
--- FAIL: TestSuites (0.00s)
    --- FAIL: TestSuites/Exhaustive (0.05s)
FAIL
exit status 1
FAIL	github.com/ramendr/ramen/e2e	561.243s
```

## Workaround

Run the entire test multiple times instead of using -count:

```
% for i in $(seq 10); do ./run.sh -run TestSuites/Exhaustive/Deploy-cephfs/Subscr; done
```

## Tasks

- [ ] Understand why the channel is not delete once at the end of all tests when running with -count=N
- [ ] Test way to mitigate this issue

### PR DESCRIPTION
**Pull request by nirs**
If we don't wait we will fail when trying to run a test again when using
-count=N or when running the test suit in a loop.

Example error:

    main_test.go:64: failed to ensure channel:
    channels.apps.open-cluster-management.io "ramen-gitops" is
    forbidden: unable to create new content in namespace ramen-samples
    because it is being terminated

Fixes #1620

### CODE REVIEW

**Review by ELENAGER — APPROVED** [review]

File: e2e/util/crud.go [hunk 1]
```diff
@@ -49,9 +50,26 @@ func DeleteNamespace(client client.Client, namespace string) error {
...
 		Ctx.Log.Info("namespace " + namespace + " not found")
+
+		return nil
 	}
 
-	return nil
+	Ctx.Log.Info("waiting until namespace " + namespace + " is deleted")
+	key := types.NamespacedName{Name: namespace}
+
+	for {
```
Comment (BenamarMk) [inline e2e/util/crud.go:60]: So this loop runs forever. No timeout, and no indication that it is running forever in case it is stuck deleting the namespace.

Comment (nirs) [reply e2e/util/crud.go:60]: There is an indication:

```go
"waiting until namespace " + namespace + " is deleted")
```

We can add a timeout, maybe using our standard timeout?

Comment (nirs) [reply e2e/util/crud.go:60]: BTW in the CI this job will fail with a timeout from our retry action. In a local run, you will have to interrupt the test process. Even if we add a timeout, you will still have to do manual cleanup to fix the env.

Comment (BenamarMk) [reply e2e/util/crud.go:60]: Sure, but from the code, it appears that deleting the namespace is the final step. This means the namespace is empty and should take no more than 5 seconds to delete. However, if the CI job times out and this message is kept as the last log entry, that should be fine.

Comment (nirs) [reply e2e/util/crud.go:60]: Turns out we don't use timeout for e2e tests, but this is easy to add and good idea anyway. But I think adding a timeout makes sense anyway and is simple.

Comment (nirs) [reply e2e/util/crud.go:63]: Added timeout, ci timeout and retries added in #1626

**Review by ShyamsundarR — APPROVED** [review]
